spring:
  cloud:
    openfeign:
      client:
        config:
          RemoteMemberService:
            url: http://localhost:8081
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
jwt:
  issuer: lgcms
  refresh_jwt_secret: helloworldshouldsecretkeysizemorebigger?moremoremoremorebiggerwhatsgoingoninthisplacerefresh
  access_jwt_secret: helloworldshouldsecretkeysizemorebigger?moremoremoremorebiggerwhatsgoingoninthisplaceaccess
  refresh_expired_time: 86400000 # 1000 * 60 * 60 * 24 = 86400000 (24시간)
  access_expired_time: 10800000 # 1000 * 60 * 60 * 3 = 10800000 (3시간)
google:
  audience: ${GOOGLE_AUDIENCE}